In [37]:
import numpy as np
from sklearn.svm import SVC
rng = np.random.RandomState(1)

In [38]:
X = rng.rand(100,10)
y = rng.binomial(1, 0.5, 100)
X_test = rng.rand(5, 10)

In [39]:
X

array([[  4.17022005e-01,   7.20324493e-01,   1.14374817e-04,
          3.02332573e-01,   1.46755891e-01,   9.23385948e-02,
          1.86260211e-01,   3.45560727e-01,   3.96767474e-01,
          5.38816734e-01],
       [  4.19194514e-01,   6.85219500e-01,   2.04452250e-01,
          8.78117436e-01,   2.73875932e-02,   6.70467510e-01,
          4.17304802e-01,   5.58689828e-01,   1.40386939e-01,
          1.98101489e-01],
       [  8.00744569e-01,   9.68261576e-01,   3.13424178e-01,
          6.92322616e-01,   8.76389152e-01,   8.94606664e-01,
          8.50442114e-02,   3.90547832e-02,   1.69830420e-01,
          8.78142503e-01],
       [  9.83468338e-02,   4.21107625e-01,   9.57889530e-01,
          5.33165285e-01,   6.91877114e-01,   3.15515631e-01,
          6.86500928e-01,   8.34625672e-01,   1.82882773e-02,
          7.50144315e-01],
       [  9.88861089e-01,   7.48165654e-01,   2.80443992e-01,
          7.89279328e-01,   1.03226007e-01,   4.47893526e-01,
          9.08595503e-01

In [40]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1])

In [41]:
X_test

array([[ 0.19255602,  0.75292591,  0.00731897,  0.3282561 ,  0.91760635,
         0.58836733,  0.85519028,  0.60467205,  0.82257815,  0.87948352],
       [ 0.32098637,  0.12295477,  0.72130334,  0.44034709,  0.12673571,
         0.58982365,  0.03606831,  0.20018212,  0.78830119,  0.01209676],
       [ 0.30334567,  0.02137596,  0.99748499,  0.58202998,  0.29337628,
         0.92894946,  0.50711942,  0.45469223,  0.58787151,  0.26413764],
       [ 0.3052883 ,  0.37165458,  0.244448  ,  0.58454727,  0.69584613,
         0.07194722,  0.97108332,  0.75307066,  0.80616316,  0.7516404 ],
       [ 0.08006098,  0.48169628,  0.44567296,  0.67247265,  0.44873726,
         0.7043134 ,  0.68164534,  0.69714853,  0.61860074,  0.15098073]])

In [42]:
from sklearn.svm import SVC
clf=SVC()
clf.set_params(kernel='linear').fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [43]:
clf.predict(X_test)

array([1, 0, 1, 0, 1])

In [44]:
clf.set_params(kernel='rbf').fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [45]:
clf.predict(X_test)

array([1, 1, 1, 1, 1])